### ISSUE TITLE
Can not open “unistd.h” for Visual Studio on Windows

### ISSUE THREAD

**Issue by adam-sim-dev** [xiaoyeli/superlu#104]
In zdriver

**Comment by gruenich** [comment]
This is a Unix header. You can install Cygwin or MinGW to get it on Windows, too.

**Comment by adam-sim-dev** [comment]
> This is a Unix header. You can install Cygwin or MinGW to get it on Windows, too.

Which functions are included in this header? Can they be replaced by stand C functions?

**Comment by gruenich** [comment]
That is a good question.
a) `unistd.h` is only used in examples and tests. SuperLU itself should work without this header.
b) Removing or replacing `unistd.h` does not solve the problem, `getopt.h` is also a header that is not provided by Windows. It is also only used in examples and tests.
c) From a quick test I believe, that both headers are used to get the function `getopt` to parse command line arguments. It might be possible to include an implementation of getopt in SuperLU and remove both headers.

@xiaoyeli what do you think, should I prepare an merge request doing c)? This would increase the portability to Windows.

**Comment by xiaoyeli** [comment]
@gruenich if you can implement getopt, that would be good.

**Comment by gruenich** [comment]
I'll have a look.

**Comment by wo80** [comment]
@xiaoyeli The `unistd.h` header was introduced in https://github.com/xiaoyeli/superlu/commit/a49ee5f535c932e6fa604eb12fac3e7796231713 ` Add #include <unistd.h> in EXAMPLE files, to get prototype for getopt().`

For testing purpose, I removed all the includes from the examples and they build just fine (Arch, GCC 13.1.1). Were there any errors on other platforms which led to the decision to include the header. Shouldn't the include of `getopt.h` be enough?

**Comment by xiaoyeli** [comment]
Removed unistd.h
