### ISSUE TITLE
Release 6.0.1?

### ISSUE THREAD

**Issue by gruenich** [xiaoyeli/superlu#106]
@xiaoyeli, what do think about releasing the current master as 6.0.1?

The fixed regression #100 would justify the change. Having a proper release would help downstream projects like PETSc.

Further, some of the fixed compiler warnings might be turned into errors with upcoming compiler versions. The improvements to CMake and Doxygen come on top.

**Comment by wuch-g2v** [comment]
+1

**Comment by gruenich** [comment]
Thank you for creating a 6.0.1 release! I am on my way to update the openSuse package.

Before I close this issue, could you please update the homepage and mention 6.0.1 there and update the most recent Doxygen documentation?

**Comment by kloczek** [comment]
Looks like it some issue with 6.0.1
```console
[ 80%] Building C object EXAMPLE/CMakeFiles/citersol.dir/cfgmr.c.o
cd /home/tkloczko/rpmbuild/BUILD/superlu-6.0.1/x86_64-redhat-linux-gnu/EXAMPLE && /usr/bin/gcc  -I/home/tkloczko/rpmbuild/BUILD/superlu-6.0.1/x86_64-redhat-linux-gnu/SRC -I/home/tkloczko/rpmbuild/BUILD/superlu-6.0.1/SRC -DUSE_VENDOR_BLAS -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -DNDEBUG -std=c99 -MD -MT EXAMPLE/CMakeFiles/citersol.dir/cfgmr.c.o -MF CMakeFiles/citersol.dir/cfgmr.c.o.d -o CMakeFiles/citersol.dir/cfgmr.c.o -c /home/tkloczko/rpmbuild/BUILD/superlu-6.0.1/EXAMPLE/cfgmr.c
/home/tkloczko/rpmbuild/BUILD/superlu-6.0.1/EXAMPLE/cfgmr.c: In function ‘cfgmr’:
/home/tkloczko/rpmbuild/BUILD/superlu-6.0.1/EXAMPLE/cfgmr.c:83:16: error: conflicting types for ‘caxpy_’; have ‘int(int *, complex *, complex *, int *, complex *, int *)’
   83 |     extern int caxpy_(int *, complex *, complex [], int *, complex [], int *);
      |                ^~~~~~
/home/tkloczko/rpmbuild/BUILD/superlu-6.0.1/EXAMPLE/cfgmr.c:38:13: note: previous declaration of ‘caxpy_’ with type ‘void(int *, complex *, complex *, int *, complex *, int *)’
   38 | extern void caxpy_(int *, complex *, complex *, int *, complex *, int *);
      |             ^~~~~~
make[2]: *** [EXAMPLE/CMakeFiles/citersol.dir/build.make:93: EXAMPLE/CMakeFiles/citersol.dir/cfgmr.c.o] Error 1
```

**Comment by wo80** [comment]
@kloczek Which BLAS provider are you using? If you intended to use the internal CBLAS provided by SuperLU, have you set `enable_internal_blaslib`?

**Comment by kloczek** [comment]
flexiblas 3.3.1

**Comment by wo80** [comment]
@kloczek Did previous versions of SuperLU compile using flexiblas? I see some changes affecting the `cfgmr` prototype in https://github.com/xiaoyeli/superlu/commit/332cf3e47ce8d56f13f3db6d4137c76e38e28d1a , but that was before the release of 6.0.0. ...

**Comment by kloczek** [comment]
> @kloczek Did previous versions of SuperLU compile using flexiblas? I see some changes affecting the `cfgmr` prototype in [332cf3e](https://github.com/xiaoyeli/superlu/commit/332cf3e47ce8d56f13f3db6d4137c76e38e28d1a) , but that was before the release of 6.0.0. ...

Just checked my build infra build logs (generated At 22 Jun) which stores record of correctly build 6.0.0 packages.

**Comment by wo80** [comment]
I think the problem might be the specified return type `void` instead of `int` of  `caxpy_` in `citersol`. Though I couldn't find a commit that affected the prototype between 6.0.0 and 6.0.1. Other examples using  `*axpy_` might also be affected.

@kloczek Could you check if changing `extern void caxpy_` to `extern int caxpy_` fixes the issue?

https://github.com/xiaoyeli/superlu/blob/d6a031ca56499eefa7c742d51fae5e8c644138cc/EXAMPLE/citersol.c#L335-L338

**Comment by wo80** [comment]
Double checked `void` should be correct. So the return type `int` in `cfgmr` is wrong, should be `void`.

https://github.com/xiaoyeli/superlu/blob/d6a031ca56499eefa7c742d51fae5e8c644138cc/EXAMPLE/cfgmr.c#L79-L82

**Comment by xiaoyeli** [comment]
I have done these.
Sherry Li

**Comment by gruenich** [comment]
Thank you for updating the documentation and the change log. The page itself still mentions v6.0.0 to be the latest... I am closing this issue, as I am fine with it.

The issue @kloczek brought up is discussed in #113, so no reason to keep this issue open.
