### ISSUE TITLE
hidden files in release tarball

### ISSUE THREAD

**Issue by nschloe** [xiaoyeli/superlu#11]
[The SuperLU 5.2.0 tarball](http://crd-legacy.lbl.gov/~xiaoye/SuperLU/superlu_5.2.0.tar.gz) contains lots of hidden files which probably shouldn't be there. In `./SRC` alone:
```
$ ls -l SRC/._* | wc -l
195
```
[The GitHub-generated tarball](https://github.com/xiaoyeli/superlu/releases/tag/v5.2.0) is a bit smaller in size and could probably be swapped in for the one distributed on [the website](http://crd-legacy.lbl.gov/~xiaoye/SuperLU/).

**Comment by xiaoyeli** [comment]
When I did the same list command, it doesn't show any hidden files.

**Comment by nschloe** [comment]
Strange.

Here's exactly what I did:
```
$ wget http://crd-legacy.lbl.gov/~xiaoye/SuperLU/superlu_5.2.0.tar.gz
[...]
$ tar xf superlu_5.2.0.tar.gz
$ ls -l SuperLU_5.2.0/SRC/._* | wc -l
195
```
Specifically, I see
```
$ cat SuperLU_5.2.0/SRC/._icmax1.c
Mac OS X        	2��ATTR��S�Scom.dropbox.attributesx��VJ)�/Hʯ�O��I�L���ON�Q�R�V�ML����%����RK�
                                                                                                            %�����HS���B�2Ê�b��@[[���Z�~
```

**Comment by xiaoyeli** [comment]
Now I see them.  I have no idea how they are generated. They are not there
in my local version.  I will make sure to clean up in the next patch,
coming soon.

**Comment by nschloe** [comment]
(I know four pull requests which wouldn't mind slipping into the next patch release either. ;))

**Comment by xiaoyeli** [comment]
I made a new tar ball v5.2.1, including your patches.

**Comment by nschloe** [comment]
The `.dropbox.attr` files are still there (just like on git master), but other than that it's looking good.

**Comment by xiaoyeli** [comment]
Just removed those. I don't know how they came up in the first place.
