### ISSUE TITLE
Assessment of the difficulty in porting CPU architecture for the superlu

### ISSUE THREAD

**Issue by wangyuliu** [xiaoyeli/superlu#118]
Hello everyone! I am working on implementing a tool to assess the complexity of CPU architecture porting. It primarily focuses on RISC-V architecture porting. As part of my dataset, I have collected the superlu project. **I would like to gather community opinions to support my assessment. I appreciate your help and response!** Based on scanning tools, the porting complexity is determined to be simple, with a small amount of code related to the CPU architecture in the project. (referring to the overall workload from adapting the project to a specific architecture to achieving full functionality on that architecture). Is this assessment accurate? I look forward to your help and response.
各位好！我在实现一个关于CPU架构的移植工作复杂度评估的工具，主要面向riscv架构移植，我收集superlu项目作为我的数据集之一，通过扫描工具得出其移植复杂度小，工程中与CPU架构相关的代码量较少，（这里指的是从工程尚未适配某架构到实现某架构的较完整功能的总体工作量）这样的判断是否准确？期待您的帮助与回答

**Comment by gruenich** [comment]
To my knowledge, SuperLU is pure C code and does not contain architecture-specific assembly. In an ideal world, you should be able to compile SuperLU for RISC-V without issues.  
Did you already try this? Did you encounter any obstacles? I think you can close this issue and if you hit any problems, open specific issues addressing these.
