### ISSUE TITLE
cmake error in "master" (endif without parentheses), commit (2c8ef7da153e87745f04f968eb2a995d735e64ec)

### ISSUE THREAD

**Issue by rustamNSU** [xiaoyeli/superlu#120]
<img width="312" alt="image" src="https://github.com/xiaoyeli/superlu/assets/54931369/73365714-f8dd-417b-a29e-569f01bece89">

**Comment by gruenich** [comment]
Thanks for opening this issue! I just created #121 to fix this. We have to wait to get this merged.
