### ISSUE TITLE
exit(1) and fprintf in ILU

### ISSUE THREAD

**Issue by LiuZhexuan** [xiaoyeli/superlu#140]
In ilu_dpivotL, if singularity is detected, exit(1) will be triggered and cause the whole program be terminated. This is inconsistent with what happend in LU. In dpivotL, singularity will only cause LU return with some error info.

The way dpivotL do is more reasonable since superLU user may want to recover from singularity (e.g. add diagnoal matrix to original matix).

**Comment by xiaoyeli** [comment]
Fixed this behavior; not to exit(1).

**Comment by gruenich** [comment]
@LiuZhexuan Can you please check the master branch, if this fixes your issues? After you confirm, we can close this.

**Comment by LiuZhexuan** [comment]
> @LiuZhexuan Can you please check the master branch, if this fixes your issues? After you confirm, we can close this.

Thanks, I pulled master branch and confirm this issue has been fixed. Please close.

**Comment by gruenich** [comment]
@xiaoyeli Please close this issue as Liu Zhexiuan confirmed it is fixed.
