### ISSUE TITLE
Unfilterable output for singular matrices

### ISSUE THREAD

**Issue by dschmitz89** [xiaoyeli/superlu#143]
This came up in scipy: https://github.com/scipy/scipy/issues/20993

On singular matrices, `SuperLU` prints some internal info to stdout which is not filterable.

**Python reproducer**

```python
import scipy
import numpy as np


A = scipy.sparse.identity(10, format='csr').tocsr()
A[-1, -1] = 0
b = np.zeros(10)
foo = scipy.sparse.linalg.spsolve(A, b)
print(foo)
```

results in

```
dgstrf info 10
[nan nan nan nan nan nan nan nan nan nan]
/tmp/ipykernel_2621/3030846931.py:8: MatrixRankWarning: Matrix is exactly singular
  foo = scipy.sparse.linalg.spsolve(A, b)
```

The scipy issue already points to the relevant lines: https://github.com/scipy/scipy/blob/1d59ab9813f052d442f5ae460f016b05aaad20a2/scipy/sparse/linalg/_dsolve/SuperLU/SRC/dgssv.c#L236

Could these lines simply be removed?

**Comment by xiaoyeli** [comment]
I removed the printing in the production mode.

**Comment by dschmitz89** [comment]
Thank you so much for the quick reaction, highly appreviated :).
