### ISSUE TITLE
complex types in cmake mixed up?

### ISSUE THREAD

**Issue by Fabian188** [xiaoyeli/superlu#144]
According to the guide, the naming scheme is
`c for single precision complex, and z for double precision complex.`

However, in cmake `enable_complex` installs `slu_cdefs.h` 
and `enable_complex16` installs `slu_zdefs.h`

In my understanding `complex16` is single precision, which leaves `complex` to the standard double precision.

**Comment by xiaoyeli** [comment]
Where did you see this in the guide?  There may be a typo.  The correct mappings are:
s - single precision real 
d - double precision real
c - single precision complex
z - double precision complex

**Comment by Fabian188** [comment]
The guide is correct, but if I enable only `enable_complex16` in cmake,  `slu_zdefs.h` is installed, and I interpret complex16 as single precision, right? If I enable only enable_complex, `slu_cdefs.h` is installed with make install. I would expect it vice versa. So the guide is correct, but IMHO not cmake.

**Comment by xiaoyeli** [comment]
if you enable_complex16, you get double precision.
if you enable_complex, you get single precision.
if you set both enabled, you get both single and double.

**Comment by Fabian188** [comment]
You are perfectly right, my bad. I mixed up single precision with 16 bits instead of 32 bits. 

But one could enhance the comments in CMakeLists.txt from

```
option(enable_single    "Enable single precision library" ON)
option(enable_double    "Enable double precision library" ON)
option(enable_complex   "Enable complex precision library" ON)
option(enable_complex16 "Enable complex16 precision library" ON)
```
to 
```
option(enable_single    "Enable single precision library" ON)
option(enable_double    "Enable double precision library" ON)
option(enable_complex   "Enable single precision complex library" ON)
option(enable_complex16 "Enable double precision complex (complex16)  library" ON)
```

**Comment by xiaoyeli** [comment]
I updated the master branch. Thanks for the suggestion.

**Comment by gruenich** [comment]
@xiaoyeli This issue can be closed. Thanks for improving the CMake code!
