### ISSUE TITLE
colamd.c has an incorrect mention of LGPL license

### ISSUE THREAD

**Issue by rgommers** [xiaoyeli/superlu#145]
We received a SciPy bug report about `colamd.c` in the vendored SuperLU code claiming that the code is under the LGPL license: https://github.com/scipy/scipy/issues/21234. The problematic mention is at: https://github.com/xiaoyeli/superlu/blob/6f7ea89bce984b61420cf9c6c1a89275e68068c7/SRC/colamd.c#L84

The code isn't actually LGPL-licensed; the BSD license mention at the top of the same file is correct, as discussed in more detail in the linked SciPy issue. The LGPL mention is still problematic, since there are now two conflicting licenses mentioned in the same file, and the LGPL mention is going to trigger extra work for Linux distro packagers and anyone else who uses license checkers to carefully analyze code for license compliance.

This problem was introduced in commit 44f2c5e47227840dfd2fe5ad890e70ff6768c1b9. The right fix I believe is to remove the offending bit of code comment that contains "LGPL". I'd be happy to open a PR for that if that helps.

**Comment by gruenich** [comment]
I think you are right. [Tim Davis' colamd](https://github.com/DrTimothyAldenDavis/SuiteSparse/tree/dev/COLAMD) is licensed under BSD-3.

Please provide a PR as this increases the changes to get this fixed.

**Comment by hawkinsp** [comment]
I think this wasn't an accident: the license *was* LGPL but it was changed at this commit; see COLAMD/Doc/License.txt

https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/75753f94f45b3bcfaf59229832c33bbd1bccf744#diff-63df1cd034960b4145afd34464072e6a66d38c76cc530659bc2f85d0695413f0

https://github.com/xiaoyeli/superlu/pull/149 updates to v4.5.6, which is the first commit after it was relicensed to BSD.
