### ISSUE TITLE
compile fail

### ISSUE THREAD

**Issue by xiaorong117** [xiaoyeli/superlu#160]
/usr/bin/ar cr /home/rong/下载/superlu-master/build/SRC/libsuperlu.a sgssv.o sgssvx.o ssp_blas2.o ssp_blas3.o sgscon.o slangs.o sgsequ.o slaqgs.o spivotgrowth.o sgsrfs.o sgstrf.o sgstrs.o scopy_to_ucol.o ssnode_dfs.o ssnode_bmod.o spanel_dfs.o spanel_bmod.o sreadhb.o sreadrb.o sreadtriple.o sreadMM.o scolumn_dfs.o scolumn_bmod.o spivotL.o spruneL.o smemory.o sutil.o smyblas2.o sgsisx.o sgsitrf.o sldperm.o ilu_sdrop_row.o ilu_ssnode_dfs.o ilu_scolumn_dfs.o ilu_spanel_dfs.o ilu_scopy_to_ucol.o ilu_spivotL.o sdiagonal.o slacon2.o superlu_timer.o util.o memory.o get_perm_c.o mmd.o sp_coletree.o sp_preorder.o sp_ienv.o relax_snode.o heap_relax_snode.o colamd.o ilu_relax_snode.o ilu_heap_relax_snode.o mark_relax.o mc64ad.o qselect.o input_error.o dmach.o smach.o
/usr/bin/ar: /home/rong/下载/superlu-master/build/SRC/libsuperlu.a: 没有那个文件或目录

**Comment by gruenich** [comment]
Can you please provide more information? What did you do? Is this compiling SuperLU or some library from you? CMake or Makefiles? Linux? What version of SuperLU? When did this happen / What was the command you executed?

Can you switch the language to English to help us understand the error message? If you run bash, execute `export LANG=C` prior to your build command.
