### ISSUE TITLE
Conflicting types for parse_command_line cmake build error

### ISSUE THREAD

**Issue by jbrzensk** [xiaoyeli/superlu#161]
Building on Linux with 
```
cmake -DCMAKE_INSTALL_PREFIX=~/USERS -DXSDK_INDEX_SIZE=64 ..
```
I get the error(s)
```
/superLU/superlu/EXAMPLE/clinsolx.c:213:1: error: conflicting types for ‘parse_command_line’; have ‘void(int,  char **, int_t *, double *, yes_no_t *, trans_t *)’ {aka ‘void(int,  char **, long int *, double *, yes_no_t *, trans_t *)’}
```
in 
clinsolx.c, dlinsolx.c, slinsolx.c, and zlinsolx.c

It all seems to be the final parse_command_line in just these four files has the third argument, an ```int_t```, instead of ```int``` in all of the other example files. Is this intentional?
https://github.com/xiaoyeli/superlu/blob/0bbd6571bd839d866bff6a8ff1eaa812a8c31463/EXAMPLE/clinsolx.c#L213C1-L214C63

 I changed the four files to just ```int```, and superLU compiled fine and completed all the tests.

**Comment by xiaoyeli** [comment]
Thanks for reporting the error. I restructured code, and fixed this error. Pushed in master.

**Comment by gruenich** [comment]
Sherry, I don't think your restructured code is a good idea. It pulls in `getops`  as a dependency to the superlu library. We only want to use it for the examples. On Windows this requires to link wingetops to superlu; this is currently not done and the build pipeline fails.

I propose:
1. Revert 7a05fcb3c7c2325e9448d4e345e8faf491cc9f80
2. Two choices
  a. Do as Jared proposed and change the four files to just  `int`.
  b. Move the four parsing into a single helper file `parsecli.h` / `.h` and include it in every example we need.

If you want, I can prepare according merge requests. Which way do you prefer?

**Comment by xiaoyeli** [comment]
I see. I'll take care of this over the weekend.

**Comment by xiaoyeli** [comment]
I reverted back, and fixed the inconsistent type specifier for *lwork. (It should be int_t, not int)

**Comment by gruenich** [comment]
Thanks, looks good to me.

@jbrzensk Can you please check and if you can confirm, close this issue?

**Comment by jbrzensk** [comment]
@xiaoyeli @gruenich This seems to have fixed it! Closing the issue. Thanks
