### ISSUE TITLE
ar: two different operation options specified

### ISSUE THREAD

**Issue by afrah** [xiaoyeli/superlu#22]
I am trying to install superlu on my ubuntu 16.04 system but I got  the following error:

> ar  -cr  /home/afrah/SuperLU_5.2.0/lib/libsuperlu_5.2.a dcomplex.o zgssv.o zgssvx.o zsp_blas2.o zsp_blas3.o zgscon.o zlangs.o zgsequ.o zlaqgs.o zpivotgrowth.o zgsrfs.o zgstrf.o zgstrs.o zcopy_to_ucol.o zsnode_dfs.o zsnode_bmod.o zpanel_dfs.o zpanel_bmod.o zreadhb.o zreadrb.o zreadtriple.o zreadMM.o zcolumn_dfs.o zcolumn_bmod.o zpivotL.o zpruneL.o zmemory.o zutil.o zmyblas2.o zgsisx.o zgsitrf.o zldperm.o ilu_zdrop_row.o ilu_zsnode_dfs.o ilu_zcolumn_dfs.o ilu_zpanel_dfs.o ilu_zcopy_to_ucol.o ilu_zpivotL.o zdiagonal.o zlacon2.o dzsum1.o izmax1.o superlu_timer.o util.o memory.o get_perm_c.o mmd.o sp_coletree.o sp_preorder.o sp_ienv.o relax_snode.o heap_relax_snode.o colamd.o ilu_relax_snode.o ilu_heap_relax_snode.o mark_relax.o mc64ad.o qselect.o input_error.o dmach.o smach.o
ranlib /home/afrah/SuperLU_5.2.0/lib/libsuperlu_5.2.a
make[1]: Leaving directory '/home/afrah/SuperLU_5.2.0/SRC'
( cd TESTING/MATGEN; make )
make[1]: Entering directory '/home/afrah/SuperLU_5.2.0/TESTING/MATGEN'
ar  -cr  ../-L/usr/lib -llibtmglib.a slatms.o slagge.o slagsy.o slarge.o slaror.o slarot.o slatm2.o slatm3.o slatm1.o slaran.o slarnd.o slaruv.o slabad.o slarnv.o \
        slatb4.o slaset.o slartg.o r_lg10.o r_sign.o pow_dd.o pow_ri.o
ar: two different operation options specified
Makefile:56: recipe for target 'single' failed
make[1]: *** [single] Error 1
make[1]: Leaving directory '/home/afrah/SuperLU_5.2.0/TESTING/MATGEN'
Makefile:39: recipe for target 'tmglib' failed
make: *** [tmglib] Error 2

here is the content of my make.inc file
`############################################################################
#
 Program:         SuperLU
#
 Module:          make.inc
#
  Purpose:         Top-level Definitions
#
 Creation date:   October 2, 1995
#
Modified:	    February 4, 1997  Version 1.0
    November 15, 1997 Version 1.1
    September 1, 1999 Version 2.0
#
############################################################################
#
The machine (platform) identifier to append to the library names
#
PLAT = _linux

#
The name of the libraries to be created/linked to
#
SuperLUroot	= /home/afrah/SuperLU_5.2.0
SUPERLULIB   	= $(SuperLUroot)/lib/libsuperlu_5.2.a

BLASDEF 	= -DUSE_VENDOR_BLAS
BLASLIB 	= -L/usr/lib/libblas -llibblas.a

TMGLIB       	= -L/usr/lib -llibtmglib.a
LIBS		= $(SUPERLULIB) $(BLASLIB) $(TMGLIB)

#
 The archiver and the flag(s) to use when building archive (library)
 If your system has no ranlib, set RANLIB = echo.
#
ARCH         = ar 
ARCHFLAGS    = -cr 
RANLIB       = ranlib

CC           = gcc
CFLAGS       = -O3 -g 
CDEFS        = -DAdd_
NOOPTS       = -O0
FORTRAN	     = /usr/bin/gfortran 
FFLAGS       = -O2 -g -fopenmp
LOADER       = $(CC)
LOADOPTS     = -fopenmp
`
Here are my ar and gcc versions:
GNU ar (GNU Binutils for Ubuntu) 2.26.1
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by xiaoyeli** [comment]
In make.inc, change

TMGLIB = -L/usr/lib -llibtmglib.a

to

TMGLIB = libtmglib.a

This is compiled in the TESTING/ directory, not in the /usr/lib directory.

Sherry Li

**Comment by afrah** [comment]
Thank you I solved it.  I want to install PDSLin1.3 ([http://portal.nersc.gov/project/sparse/pdslin/] I installed all dependecies but now when running make, I keep getting this error:

...// warnings
/home/afrah/pdslin/include/pdslin_slu.h:49:24: error: unknown type name ‘superlu_options_t’
 void get_perm_c_dist_t(superlu_options_t *options, int_t pnum, int_t ispec, SuperMat
                        ^
/home/afrah/pdslin/include/pdslin_slu.h:70:24: error: unknown type name ‘superlu_options_t’
 int_t pdslin_symbfact( superlu_options_t *options, /* input options */
.
.
.
<command-line>:0:0: note: this is the location of the previous definition
get_perm_c.c:49:11: error: unknown type name ‘superlu_options_t’
           superlu_options_t *options,
           ^
get_perm_c.c:167:19: error: unknown type name ‘superlu_options_t’
 get_perm_c_dist_t(superlu_options_t *options, int_t pnum, int_t ispec, SuperMatrix *
 makefile:41: recipe for target 'get_perm_c.o' failed
make[2]: *** [get_perm_c.o] Error 1
make[2]: Leaving directory '/home/afrah/pdslin/src/slu'
makefile:46: recipe for target 'lib' failed
make[1]: *** [lib] Error 2
make[1]: Leaving directory '/home/afrah/pdslin/src'
makefile:8: recipe for target 'all' failed
make: *** [all] Error 2

This is my make file:
#
//# top directory make.inc
# 
//# on hopper: % module load cray-petsc which also loads cray-tpsl, including pt-schotch and parmetis.

//########################################################################
//# home directory, where the software is located
TOP  = /home/afrah/pdslin
HOME = $(TOP)/examples
INCLUDEDIR =/usr/include
//########################################################################
//# hybrid solver library name
LIB  = $(TOP)/lib/libhybrid.a

//########################################################################
//# make utility
MAKE = make

//########################################################################
//# archiver and flags to build the library
ARCH         = /usr/bin/ar
ARCHFLAGS    = cr
RANLIB       = /usr/bin/ranlib
//########################################################################
//# C compiler and flags
CC           = cc
CFLAGS 	     = -O3 -llibblas -lliblapack -llibparmetis -llibmetis -DDEBUGlevel=0 -DPRNTlevel=0  -DPROFlevel=0  -g --verbose 
CFLAGS       += -DAdd_
CFLAGS       +=  -D_LONGINT
CFLAGS       +=  -D_OPENMP
NOOPTS       = -O0

//#FLAGS = -c99 -fastsse -DWITH_PETSC -DPETSC3_1 ${IPM}
//#FLAGS = -fast -Mipa=fast,safe -DWITH_PETSC ${IPM} 
//       	## -DSCOTCH_METIS_PREFIX
//#FLAGS 	+= -DWITH_PETSC
//# FLAGS 	+= -DMETIS_V4
FLAGS	+= -DSCOTCH_METIS_PREFIX
FLAGS += -DISORT -DISORT1   ## defined in SuperLU_DIST_3.3, but not earlier versions

//########################################################################
//# fortran compiler and flags
FC     = /usr/share/mpich-install/bin/mpif90
//# FLIB   = -pgcpplibs -lpgf90 -lpgf90_rpm1 -lpgf902 -lpgf90rtl -lpgftnrtl
//#FFLAGS = -fast -Mipa=fast,safe
FFLAGS       = -O3 -llibmpi.so -lpthread -llibblas -lliblapack -llibparmetis -llibmetis -DDEBUGlevel=0 -DPRNTlevel=0  -DPROFlevel=0 -g  -lz

//########################################################################
//# linker used to link example program with the library
LINKER = /usr/share/mpich-install/bin/mpicc -Wl,--allow-multiple-definition
//# LINKER = cc

//########################################################################
//# C++ compiler (this is not needed for your standard compilation)
CPP = /usr/share/mpich-install/bin/mpicxx


//########################################################################
//# Libraries:
//#
//# MPI/BLAS libraries
L_MPI =  -L/usr/share/mpich-install/lib -llibmpich
I_MPI =  -I/usr/share/mpich-install/include
L_BLAS = -llibblas -lliblapack
//####################################################################

L_PPART = -L/usr/share/parmetis/lib/libmetis.a -lmetis \
          -L/usr/share/parmetis/lib/libparmetis.so -lparmetis 

I_PPART = -I/usr/local/include 


L_PPART =  -L/usr/local/lib  -llibscotch -llibscotcherr -llibptscotch -lptscotch  \
           -L/usr/local/lib  -lptscotcherr  -llibscotchmetis -lptscotchparmetis 
I_PPART = -DSCOTCH_ORDER -I/usr/local/include

//#------------------------------------------------------#
//# SuperLU_DIST library, and its header files  (hopper: module load superlu_dist)
//# SLUDIST = /global/common/hopper2/acts/SuperLU/SuperLU_DIST/2.5
//# L_SLUDIST = -L$(SLUDIST)/craypgi-xe6_O/lib -lsuperlu_dist_2.5
//# I_SLUDIST = -DDEBUGlevel=0 -DPRNTlevel=1 -DAdd_ -DUSE_VENDOR_BLAS -I$(SLUDIST)/SRC 

I_SLUDIST = -DDEBUGlevel=0 -DPRNTlevel=0 -DAdd_ -DUSE_VENDOR_BLAS -I/home/afrah/SuperLU_DIST_5.1.2/SRC
L_SLUDIST =  /home/afrah/SuperLU_DIST_5.1.2/lib/libsuperlu_dist.so


//#------------------------------------------------------#
//# Metis Library, and its header files
L_METIS = -L/usr/share/parmetis/lib/libmetis.a -lmetis
I_METIS =  /usr/share/parmetis/include

//#------------------------------------------------------#
//# Other optional libraries

//# serial SuperLU
L_SLU = -L/home/afrah/SuperLU_5.2.0/lib/libsuperlu_5.2.a -llibsuperlu
I_SLU = /home/afrah/SuperLU_5.2.0/SRC


//########################################################################
//########################################################################
//# accumulate all includes and libraries

INC  = -I$(TOP)/include $(I_SLU) $(INCLUDEDIR) $(I_SLUDIST) $(I_PPART) $(I_METIS)  $(I_MPI) 
LIBS = $(LIB) $(L_SLUDIST) $(L_PPART) $(L_METIS) $(L_BLAS) $(L_MPI) $(L_SLU)
ZLIBS = $(LIB)  $(L_SLUDIST)  $(L_PPART) $(L_METIS) $(L_BLAS) $(L_MPI)
