### ISSUE TITLE
SuperLU with 64 bit integers

### ISSUE THREAD

**Issue by ghareg** [xiaoyeli/superlu#24]
[makeSLU.txt](https://github.com/xiaoyeli/superlu/files/1337921/makeSLU.txt)
[makeSLUMT.txt](https://github.com/xiaoyeli/superlu/files/1337922/makeSLUMT.txt)

Hi I am having problem of using SuperLU because of large number of nnz = 131000000. So when it tries to create work array the size of the array becomes larger than max array size and it gives the error "Not enough memory to perform factorization.". I don't have an issue in terms of the memory, because I am running it on shared memory machine with large RAM, so the issue is due to the 32 bit integer. As far as I can understand there is no solution to this in SuperLU, but SuperluMT has a way of handling 64 bit integers. While I was able to install SuperLU I wasn't able to make the SuperluMT to work. I am linking with Intel MKL library and using intel compilers. Please see the make option files for both cases attached. For SuperluMT I always get segmentation errors even during testing. Also I am using SuperLU with Arpack, therefore I am not sure if I compile 64 bit option of SuperLU how I should run it with Arpack. Any type of advice will be helpful.

Thank you,
Areg Ghazaryan

**Comment by yoda90** [comment]
Same Problem here. I want to compile with 64 bit integers but this seems not to be possible.

**Comment by xiaoyeli** [comment]
This is available in v6.0 now.
