### ISSUE TITLE
Errors in compiling zschur_sludist.c

### ISSUE THREAD

**Issue by chang-l** [xiaoyeli/superlu#27]
Hi Sherry,
I am trying to install PDSLin(2.2.0). But I encountered some problems during compiling stage..
The package is installed on lonestar5 at TACC with the following setup (make.inc):

######################################################################
# Top directory make.inc
########################################################################
# home directory, where the software is located
TOP = ${HOME}
PDSLIN_TOP = $(TOP)/lib/pdslin
########################################################################
# hybrid solver library name
LIB  = $(PDSLIN_TOP)/lib/libpdslin.a

########################################################################
# make utility
MAKE = make

########################################################################
# archiver and flags to build the library
ARCH      = ar
ARCHFLAGS = -cr

########################################################################
# C compiler, and flags
CC    = mpicc
FLAGS = -g -O0 -fopenmp -std=c99  -DWITH_PETSC

########################################################################
# Fortran compiler and flags
FC     = mpif90
FLIB   =
FFLAGS =

########################################################################
# linker to link example programs to the library
LINKER =  CC -Wl,--allow-multiple-definition

########################################################################
# C++ compiler (this is not needed for your standard compilation)
CPP = mpicxx

########################################################################
# Libraries:
#
# BLAS/MPI libraries, and MPI include
L_BLAS =
L_MPI =
I_MPI =

#------------------------------------------------------#
# parallel partitioning library, and its header files
L_PPART = -L${TACC_PMETIS_LIB}
I_PPART = -I${TACC_PMETIS_INC} -lparmetis -lmetis

#------------------------------------------------------#
# Metis library, and its header files
L_METIS = -L${TACC_METIS_LIB}
I_METIS = -I${TACC_METIS_INC} -lmetis

#------------------------------------------------------#
# SuperLU_DIST library, and its header files
I_SLUDIST = -DDEBUGlevel=0 -DPRNTlevel=0 -DAdd_ -DUSE_VENDOR_BLAS -I${TACC_SUPERLU_INC}
L_SLUDIST = -L${TACC_SUPERLU_LIB}/lib

#------------------------------------------------------#
# Petsc library, and its header files
# double version
#I_PETSC = -I/opt/apps/intel16/cray_mpich_7_3/petsc/3.7/include
#          -I/opt/apps/intel16/cray_mpich_7_3/petsc/3.7/haswell-complex/include

#L_PETSC = -L/opt/apps/intel16/cray_mpich_7_3/petsc/3.7/haswell-complex/lib -llibpetsc

# complex (edison: module load cray-petsc-complex)
 I_ZPETSC = -I$(PETSC_DIR)/include -I${PETSC_DIR}/${PETSC_ARCH}/include
 L_ZPETSC = -L${PETSC_DIR}/${PETSC_ARCH}/lib -lpetsc

#------------------------------------------------------#
# Other optional libraries
# HIPS to extract subdomains
I_HIPS =

L_HIPS =

# serial SuperLU
I_SLU =
L_SLU =
########################################
# accumulate all includes and libraries
INC  = -I$(PDSLIN_TOP)/include $(I_CDF) $(I_HIPS) $(I_SLU) $(I_SLUDIST) $(I_PPART) $(I_METIS) $(I_MUMPS)  $(I_ZPETSC) $(I_PATOH) $(I_MPI)       
#LIBS = $(LIB) $(L_CDF) $(L_HIPS) $(L_PETSC) $(L_SLU) $(L_SLUDIST) $(L_MUMPS) $(L_PATOH) $(L_PPART) # $(L_METIS) -mkl $(L_MPI) $(FLIB)
ZLIBS = $(LIB) $(L_CDF) $(L_HIPS) $(L_ZPETSC) $(L_SLU) $(L_SLUDIST) $(L_MUMPS) $(L_PATOH) $(L_PPART) $(L_METIS) -mkl $(L_MPI) $(FLIB)
        

I skipped PT-SCOTCH pkg because we have ParMetis available (slightly modified the src code removing header of scotch).  When I compile the src/ with:
make zlib; 

It reported the following errors from zschur_sludist.c file:

mpicc -c -I/home1/02802/chang/lib/pdslin/include    -DDEBUGlevel=0 -DPRNTlevel=0 -DAdd_ -DUSE_VENDOR_BLAS -I/opt/apps/intel16/cray_mpich_7_3/petsc/3.7/haswell-complex/include -I/opt/apps/intel16/cray_mpich_7_3/pmetis/4.0.2/include -lparmetis -lmetis -I/opt/apps/intel16/metis/5.0.2/include -lmetis  -I/opt/apps/intel16/cray_mpich_7_3/petsc/3.7//include -I/opt/apps/intel16/cray_mpich_7_3/petsc/3.7//haswell-complex/include   -g -O0 -fopenmp -std=c99  -DWITH_PETSC  zschur_sludist.c
**_zschur_sludist.c(118): error: struct "<unnamed>" has no field "xrow_to_proc"
    SOLVEstruct->xrow_to_proc = NULL;
                 ^
zschur_sludist.c(213): error: struct _"<unnamed>"_ has no field "xrow_to_proc"
            if( SOLVEstruct->xrow_to_proc == NULL ) assert( (SOLVEstruct->xrow_to_proc = intMalloc_dist(A->nrow)) );
                             ^
zschur_sludist.c(213): error: struct "<unnamed>" has no field "xrow_to_proc"
            if( SOLVEstruct->xrow_to_proc == NULL ) assert( (SOLVEstruct->xrow_to_proc = intMalloc_dist(A->nrow)) );
                                                    ^
zschur_sludist.c(262): error: struct "<unnamed>" has no field "xrow_to_proc"
                SOLVEstruct->xrow_to_proc[i] = p;
                             ^
zschur_sludist.c(276): error: struct "<unnamed>" has no field "xrow_to_proc"
                    SOLVEstruct->xrow_to_proc[i] = p+1;
                                 ^
zschur_sludist.c(305): error: struct "<unnamed>" has no field "xrow_to_proc"
            zpdslin_slu_allocate_buffers( n, blk, SOLVEstruct->xrow_to_proc, grid, Glu_persist, SOLVEstruct );_**

I am not a C programmer so I am wondering what happened....
Could you help me on that?
Thanks,
Chang

**Comment by gruenich** [comment]
I think you wanted to use superlu-mt which has support for OpenMP. Can this bug be closed?

**Comment by xiaoyeli** [comment]
@chang-l @gruenich 
Sorry I missed this issue before.  It appears that the TACC installation of superlu_dist is probably a much older version; it doesn't have "xrow_to_proc" definition, which is needed to support PDSLin. 
The newer version should have it defined in superlu_ddefs.h and superlu_zdefs.h (complex)
