### ISSUE TITLE
Thread-safety issue in sequential superLU

### ISSUE THREAD

**Issue by coronasky** [xiaoyeli/superlu#28]
Hi Sherry,

It seems there are some places in the sequential superLU where local static variables are used. This might cause thread-safety issues if the same function is called by multiple threads. Would you please help take a look?
For example superlu/SRC/icmax1.c:66
    static float smax;
    static int i, ix;

Regards,
Haotian

**Comment by xiaoyeli** [comment]
You can remove static in both icmax1.c & izmax1.c.  These were translated from Fortran using f2c, which inserted static. 

I will update the master branch.

**Comment by coronasky** [comment]
Hi Sherry,

Thanks for the quick response!

-Haotian
