### ISSUE TITLE
Uses of deprecated function not available anymore in openmpi 4.

### ISSUE THREAD

**Issue by arbolis** [xiaoyeli/superlu#29]
From https://bitbucket.org/petsc/petsc/issues/260/compatibility-with-openmpi-4, it was determined that "It looks like SuperLU_Dist is using a deprecated function (MPI_Attr_get) which OpenMPI-4 no longer supports. You can report this to SuperLU, and maybe use MUMPS instead for now."

**Comment by xiaoyeli** [comment]
I have changed to MPI_Comm_get_attr()
