### ISSUE TITLE
Possible absolute path in superlu build.

### ISSUE THREAD

**Issue by ColumPaget** [xiaoyeli/superlu#30]
Hiya,

When building superlu (on a linux-from-scratch system) I get the below error. It looks like ar is using an absolute path when it shouldn't be, but I might be doing something wrong.

regards,

Colum

/usr/bin/ar cr /home/xiaoye/Dropbox/Codes/SuperLU/SuperLU_5.2.1/build/SRC/libsuperlu.a sgssv.o sgssvx.o ssp_blas2.o ssp_blas3.o sgscon.o slangs.o sgsequ.o slaqgs.o spivotgrowth.o sgsrfs.o sgstrf.o sgstrs.o scopy_to_ucol.o ssnode_dfs.o ssnode_bmod.o spanel_dfs.o spanel_bmod.o sreadhb.o sreadrb.o sreadtriple.o scolumn_dfs.o scolumn_bmod.o spivotL.o spruneL.o smemory.o sutil.o smyblas2.o sgsisx.o sgsitrf.o sldperm.o ilu_sdrop_row.o ilu_ssnode_dfs.o ilu_scolumn_dfs.o ilu_spanel_dfs.o ilu_scopy_to_ucol.o ilu_spivotL.o sdiagonal.o slacon2.o superlu_timer.o util.o memory.o get_perm_c.o mmd.o sp_coletree.o sp_preorder.o sp_ienv.o relax_snode.o heap_relax_snode.o colamd.o ilu_relax_snode.o ilu_heap_relax_snode.o mark_relax.o mc64ad.o qselect.o input_error.o smach.o dmach.o smach.o
/usr/bin/ar: /home/xiaoye/Dropbox/Codes/SuperLU/SuperLU_5.2.1/build/SRC/libsuperlu.a: No such file or directory

**Comment by gruenich** [comment]
This was fixed in the meantime, SuperLU 5.2.2 no longer contains the term Dropbox besides the variable `SuperLUroot` in some of the `MAKE_INC/make.*` files, that should be adopted anyway.
Can you retest with 5.2.2 and close this bug, if it is fixed for you?
