### ISSUE TITLE
Can superlu solve the symmetric matrix?

### ISSUE THREAD

**Issue by zrjer** [xiaoyeli/superlu#42]
Hello, I have a question. The example dlinsol1 uses  DGSSV in the symmetric mode. Does it mean superlu can deal with symmetric matrix or just regard the symmetrix matrix as a general matrix? Thank you!

**Comment by xiaoyeli** [comment]
You will still need to input the full matrix, both lower part and upper
part.
See this FAQ for description:
https://portal.nersc.gov/project/sparse/superlu/faq.html#sym-problem

Sherry Li
