### ISSUE TITLE
Can not compile/Execute SuperLU test example

### ISSUE THREAD

**Issue by ChrisNabold** [xiaoyeli/superlu#45]
I installed SuperLU -5.5.2 in C:/superLU-5.5.2. With CMake I created c:\superLU-5.5.2, make make install
This created c:\program files (x86)/superLU/inclue and lib with the following subfolders cmake, pkconfig and the two elements libblas.a and libsuperlu.a
How can I create a libsuberlu.a which inliudes OpenBlas (installed in directory c:/openblas?

**Comment by xiaoyeli** [comment]
Please take a look at README:  https://github.com/xiaoyeli/superlu
It has the following instruction for BLAS:

You should link with a fast BLAS library by specifying the following:
              -DTPL_BLAS_LIBRARIES=<blas_library_name>
