### ISSUE TITLE
buid and install on the windows

### ISSUE THREAD

**Issue by Ethan-GitHub** [xiaoyeli/superlu#51]

**Comment by Ethan-GitHub** [comment]
hi, 
I did not find the make.inc for windows in the MAKE_INC file. 
I want to build the SuperLU on the windows used "MinGW” by the cmake. and i do not want to use the external "libblas.lib" not  the internal CBLAS lib.
who can help me ?

i try to run the cmake command, but the building result is libsuperlu.a for linnux not the lib for windows.
```cmake
cmake ^
-D CMAKE_CXX_COMPILER=D:\mingw64\bin\g++.exe ^
-D CMAKE_C_COMPILER=D:\mingw64\bin\gcc.exe ^
-D CMAKE_Fortran_COMPILER=D:\mingw64\bin\gfortran.exe ^
-Wno-dev ^
-D enable_internal_blaslib=NO ^
-D BLAS_blas_LIBRARY=E:\Peraglobal-maolin.wang\Perasim\Perasim-svn\PERASIM.SolveT\trunk\LAPACK\LAPACK-win\install\lib\libblas.lib ^
-D CMAKE_INSTALL_PREFIX=E:\Peraglobal-maolin.wang\Perasim\Perasim-svn\PERASIM.SolveT\trunk\SuperLU\Windows\install\SuperLU ^
E:\Peraglobal-maolin.wang\Perasim\Perasim-svn\PERASIM.SolveT\trunk\SuperLU\SuperLU\superlu
``

make
make install

**Comment by xiaoyeli** [comment]
We don't know how CMake works for Windows. I think you can build manually. 
Please take a look at the FAQ page:
https://portal.nersc.gov/project/sparse/superlu/faq.html#windows

**Comment by Ethan-GitHub** [comment]
The way of building with Visual Studio for Windows is OK!
thanks for your help.

**Comment by Ning-Li-Ambition** [comment]
Hello Ethan, have you successfully installed superLU on windows and used it with visual studio projects? I built the superLU_MT library with visual studio without errors. but when I linked it to my own visual studio project, I got some link errors. Could you give me some help? Thanks
