### ISSUE TITLE
Issue when calling SuperLU from threads under windows

### ISSUE THREAD

**Issue by SanPen** [xiaoyeli/superlu#58]
Hello, 

I am making a progran to simulate electrical circuits using Armadillo, MKL and SuperLU.
When I run my simulations in serial mode everything goes as expected; No multi-threading anywhere, all linked libraries are the single-threaded version.

However, under windows, when I run the simulation from a parrallel for loop, the cores are not beign used the 100%, indicating some sort of race condition. This is not observed for Linux or MacOS.

I even posted a [SO question](https://stackoverflow.com/questions/70410562/c-parallel-program-is-very-slow-on-windows-threading) to see if I was doing something wrong. It is also wrth noting, that for any simulation, the sparse matrix factorization is about 45% of the runtime. So SuperLU is used a lot.

After quiete some tinkering (even compiled with MinGW, made sure every object was read-only, etc...) I found that if I change the spasolver in armadillo from "superlu" to "lapack" the 100% of all cores is used, hence superlu is the problem. 

Of course, Lapack is awfully slow for my problem and I need SuperLU. Hence this question.

**Is there anything I should do to make SuperLu "unlock" the threads on windows?**

**Is SuperLU thread-safe?**

Thanks in advance.

**Comment by xiaoyeli** [comment]
As far as I know, serial SuperLU is thread-safe.  I don't understand why "cores under utilized" is related to "race condition".  In serial SuperLU, there are no atomic operations.

**Comment by SanPen** [comment]
Hi, 

This is something I've observed, and I have no means to fix, hence the question.

I'll see if I can prepare a simple .h file so that you can observe the behaviour as well.
