### ISSUE TITLE
question of symbfact

### ISSUE THREAD

**Issue by Wangtc525** [xiaoyeli/superlu#62]
Hello, excuse me, I want to see the matrix after symbol decomposition, but I can't find a way to output, is there any way, thank you

**Comment by Wangtc525** [comment]
> Hello, excuse me, I want to see the matrix after symbol decomposition, but I can't find a way to output, is there any way, thank you

**Comment by Wangtc525** [comment]
It doesn't matter, I first tried to output the matrix of row and column permutation later, which I could do, but when it came to symbolic decomposition, I was confused by Etree and Supernode. Although I looked at {L, U}data structures, the structure of the inside puzzled me, I still couldn't find a correct way to view the matrix after symbolic decomposition.Anyway, thank you for your letter～
















At 2022-03-24 00:28:58, "X. Sherry Li" ***@***.***> wrote:

Sorry I forgot to reply. Did you find where to look for the {L, U} data structures?

**Comment by xiaoyeli** [comment]
Section 2.3 of the Users Guide explains various matrix structures, with a small example:
https://portal.nersc.gov/project/sparse/superlu/ug.pdf

In SRC/dutil.c, there are several print routines to print the matrices, e.g., dPrint_SuperNode_Matrix()

**Comment by Wangtc525** [comment]
wow,thank you!!!

You gave me a good direction and a good solution！













At 2022-03-24 04:58:29, "X. Sherry Li" ***@***.***> wrote:

Section 2.3 of the Users Guide explains various matrix structures, with a small example:
https://portal.nersc.gov/project/sparse/superlu/ug.pdf

In SRC/dutil.c, there are several print routines to print the matrices, e.g., dPrint_SuperNode_Matrix()
