### ISSUE TITLE
need : libsuperlu.so.5.1

### ISSUE THREAD

**Issue by Ashutosh-432** [xiaoyeli/superlu#67]
Hi Team 

I need this  [ libsuperlu.so.5.1 ] file for my project.

but After i installed i found :
![image](https://user-images.githubusercontent.com/104203359/201319144-1d17217e-f5a7-4eb5-88c8-7c8ed7dec950.png)

which is [ libsuperlu.a ] file .  

could you pls help me how can i found  [ libsuperlu.so.5.1 ] this file .

**Comment by xiaoyeli** [comment]
You need to install SuperLU as a dynamic library.
Also, 5.1 is quite old.  The latest is 5.3

**Comment by Ashutosh-432** [comment]
Hi @xiaoyeli  
could you pls share me some link  or steps  on ,
How to install SuperLU as a dynamic library . 
And i need 5.1 , as our old  project is already build  on that.
Thanks for your help.

**Comment by xiaoyeli** [comment]
If you use Cmake to install, you can specify:
-DBUILD_SHARED_LIBS=ON

Otherwise, you have to check your compiler and the flag for this.
