### ISSUE TITLE
enable_blaslib misnamed?

### ISSUE THREAD

**Issue by nschloe** [xiaoyeli/superlu#7]
I played around with the CMake build and found the variable `enable_blaslib` a bit strange. If `TRUE`, BLAS is _always_ built as part of SuperLU, never taken from the system. Is this intentional?

**Comment by xiaoyeli** [comment]
By default enable_blaslib is considered to be FALSE, then either you define a TPL_BLAS_LIBRARIES, or find_package(BLAS) will find one on your machine.

You can set -DENABLE_BLAS=TRUE, then the internal BLAS will be built from CBLAS/ directory.

**Comment by nschloe** [comment]
Yes. Perhaps `BUILD_BLASLIB` would be a more appropriate name for the variable.

**Comment by gruenich** [comment]
With SuperLU 5.2.2 / e387cae9c37963dd976071f7f1c1f38dfb9118d6  `enable_blaslib` got renamed to `enable_internal_blaslib`. This should settle this issue and thus it can be closed, right?
